# Eat Safe, Love

## Notebook Set Up

In [1]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [4]:
# review the collections in our database
collections = db.list_collection_names()
print("Collections in 'uk_food' database:", collections)

Collections in 'uk_food' database: ['establishments']

In [6]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [7]:
# Find the establishments with a hygiene score of 20
query = {"scores.Hygiene": 20}

# Use count_documents to display the number of documents in the result
count = db.establishments.count_documents(query)
print(f"Number of establishments with a hygiene score of 20: {count}")
# Display the first document in the results using pprint
first_result = db.establishments.find_one(query)
print("\nFirst establishment with a hygiene score of 20:")
pprint(first_result)

Number of establishments with a hygiene score of 20: 41

First establishment with a hygiene score of 20:
{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6707eeb121bc4028575cf35a'),
 'geocode': {'latitude': 50.769705, 'longitude': 0.27694},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [38]:
# Convert the result to a Pandas DataFrame
cursor = db.establishments.find(query)
results = list(cursor)  # Convert cursor to list to load into DataFrame
df = pd.DataFrame(results)

# Display the number of rows in the DataFrame
num_rows = len(df)
print(f"\nNumber of rows in the DataFrame: {num_rows}")
# Display the first 10 rows of the DataFrame
print("\nFirst 10 rows of the DataFrame:")
print(df.head(10))

Number of rows in the DataFrame: 41

First 10 rows of the DataFrame:
                        _id   FHRSID  ChangesByServerID  \
0  670711112bbdead17cb96358   110681                  0
1  670711112bbdead17cb966d9   612039                  0
2  670711122bbdead17cb969e3   730933                  0
3  670711122bbdead17cb96bcf   172735                  0
4  670711122bbdead17cb96be0   172953                  0
5  6707111a2bbdead17cb9757f   512854                  0
6  6707111a2bbdead17cb977a0  1537089                  0
7  670711202bbdead17cb98ccb   155648                  0
8  670711212bbdead17cb9910f  1012883                  0
9  670711222bbdead17cb99921   644109                  0

  LocalAuthorityBusinessID               BusinessName  \
0                     4029        The Chase Rest Home
1                1970/FOOD                 Brenalwood
2                1698/FOOD              Melrose Hotel
3             PI/000023858              Seaford Pizza
4             PI/000024532              Golden Palace
5            12/00816/BUTH           Ashby's Butchers
6          22/00224/RESTUN  South Sea Express Cuisine
7              EH/00006058              Golden Palace
8         17/00110/MIXED/S             The Tulip Tree
9                    41811                      F & S

                        BusinessType  BusinessTypeID           AddressLine1  \
0                    Caring Premises               5   5-6 Southfields Road
1                    Caring Premises               5              Hall Lane
2  Hotel/bed & breakfast/guest house            7842  53 Marine Parade East
3             Takeaway/sandwich shop            7844          4 High Street
4            Restaurant/Cafe/Canteen               1         5 South Street
5                  Retailers - other            4613   777 Southchurch Road
6            Restaurant/Cafe/Canteen               1    33 Alexandra Street
7             Takeaway/sandwich shop            7844          7 London Road
8            Restaurant/Cafe/Canteen               1          3 The Village
9                  Retailers - other            4613

         AddressLine2 AddressLine3  ...  \
0          Eastbourne  East Sussex  ...
1  Walton-on-the-Naze        Essex  ...
2      Clacton On Sea        Essex  ...
3             Seaford  East Sussex  ...
4             Seaford  East Sussex  ...
5     Southend-On-Sea        Essex  ...
6     Southend-on-sea        Essex  ...
7            Rayleigh        Essex  ...
8       Chiddingstone         KENT  ...
9      81 Southernhay     Basildon  ...

                      LocalAuthorityWebSite  \
0  http://www.eastbourne.gov.uk/foodratings
1             http://www.tendringdc.gov.uk/
2             http://www.tendringdc.gov.uk/
3       http://www.lewes-eastbourne.gov.uk/
4       http://www.lewes-eastbourne.gov.uk/
5                http://www.southend.gov.uk
6                http://www.southend.gov.uk
7                http://www.rochford.gov.uk
8              http://www.sevenoaks.gov.uk/
9                http://www.basildon.gov.uk

              LocalAuthorityEmailAddress  \
0        Customerfirst@eastbourne.gov.uk
1             fhsadmin@tendringdc.gov.uk
2             fhsadmin@tendringdc.gov.uk
3    ehealth.ldc@lewes-eastbourne.gov.uk
4    ehealth.ldc@lewes-eastbourne.gov.uk
5    EnvironmentalHealth@southend.gov.uk
6    EnvironmentalHealth@southend.gov.uk
7       customerservices@rochford.gov.uk
8  environmental.health@sevenoaks.gov.uk
9                    ehs@basildon.gov.uk

                                              scores  SchemeType  \
0  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...        FHRS
1  {'Hygiene': 20, 'Structural': 15, 'ConfidenceI...        FHRS
2  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...        FHRS
3  {'Hygiene': 20, 'Structural': 10, 'ConfidenceI...        FHRS
4  {'Hygiene': 20, 'Structural': 10, 'ConfidenceI...        FHRS
5  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...        FHRS
6  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...        FHRS
7  {'Hygiene': 20, 'Structural': 15, 'ConfidenceI...        FHRS
8  {'Hygiene': 20, 'Structural': 5, 'ConfidenceIn...        FHRS
9  {'Hygiene': 20, 'Structural': 20, 'ConfidenceI...        FHRS

                                             geocode RightToReply  \
0      {'longitude': 0.27694, 'latitude': 50.769705}
1     {'longitude': 1.278721, 'latitude': 51.857536}
2      {'longitude': 1.15927, 'latitude': 51.789429}
3      {'longitude': 0.10202, 'latitude': 50.770885}
4     {'longitude': 0.101446, 'latitude': 50.770724}
5     {'longitude': 0.736349, 'latitude': 51.541448}
6   {'longitude': 0.7121671, 'latitude': 51.5350065}
7     {'longitude': 0.602364, 'latitude': 51.591515}
8  {'longitude': 0.146449998021126, 'latitude': 5...
9      {'longitude': 0.462307, 'latitude': 51.57005}

      Distance NewRatingPending  \
0  4613.888288            False
1  4617.965824            False
2  4619.656144            False
3  4620.421725            False
4  4620.437179            False
5  4625.565258            False
6  4626.200132            False
7  4632.276890            False
8  4633.934041            False
9  4636.552523            False

                                                meta  \
0  {'dataSource': None, 'extractDate': '0001-01-0...
1  {'dataSource': None, 'extractDate': '0001-01-0...
2  {'dataSource': None, 'extractDate': '0001-01-0...
3  {'dataSource': None, 'extractDate': '0001-01-0...
4  {'dataSource': None, 'extractDate': '0001-01-0...
5  {'dataSource': None, 'extractDate': '0001-01-0...
6  {'dataSource': None, 'extractDate': '0001-01-0...
7  {'dataSource': None, 'extractDate': '0001-01-0...
8  {'dataSource': None, 'extractDate': '0001-01-0...
9  {'dataSource': None, 'extractDate': '0001-01-0...

                                               links
0  [{'rel': 'self', 'href': 'https://api.ratings....
1  [{'rel': 'self', 'href': 'https://api.ratings....
2  [{'rel': 'self', 'href': 'https://api.ratings....
3  [{'rel': 'self', 'href': 'https://api.ratings....
4  [{'rel': 'self', 'href': 'https://api.ratings....
5  [{'rel': 'self', 'href': 'https://api.ratings....
6  [{'rel': 'self', 'href': 'https://api.ratings....
7  [{'rel': 'self', 'href': 'http://api.ratings.f...
8  [{'rel': 'self', 'href': 'http://api.ratings.f...
9  [{'rel': 'self', 'href': 'http://api.ratings.f...

[10 rows x 28 columns]

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [10]:
# Define the query to find establishments in London with a RatingValue >= 4
query = {
    "LocalAuthorityName": {"$regex": r"\bLondon\b", "$options": "i"},
    "RatingValue": {"$gte": 4}  # RatingValue greater than or equal to 4
}

# Use count_documents to display the number of documents in the result
count = db.establishments.count_documents(query)
print(f"Number of establishments in London with a RatingValue >= 4: {count}")

# Retrieve the first document in the results
first_document = db.establishments.find_one(query)

# Display the first document in the results using pprint
if first_document:
    print("\nFirst document in the results:")
    pprint(first_document)
else:
    print("No establishments found in London with a RatingValue >= 4.")

Number of establishments in London with a RatingValue >= 4: 33

First document in the results:
{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('6707eeb221bc4028575d0d78'),
 'geocode': {'latitude': 51.369321, 'longitude': 0.508551},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [11]:
# Convert the result to a Pandas DataFrame
results = db.establishments.find(query)
df = pd.DataFrame(list(results))
# Display the number of rows in the DataFrame
num_rows = df.shape[0]
print(f"Number of rows in the DataFrame: {num_rows}")
# Display the first 10 rows of the DataFrame
print("\nFirst 10 rows of the DataFrame:")
print(df.head(10))

Number of rows in the DataFrame: 33

First 10 rows of the DataFrame:
                        _id   FHRSID  ChangesByServerID  \
0  6707eeb221bc4028575d0d78   621707                  0
1  6707eeb221bc4028575d109e  1130836                  0
2  6707eeb221bc4028575d1beb   293783                  0
3  6707eeb221bc4028575d29ea  1315095                  0
4  6707eeb221bc4028575d29ec   294474                  0
5  6707eeb321bc4028575d30f2   294900                  0
6  6707eeb421bc4028575d5202   293756                  0
7  6707eeb421bc4028575d55d3   878523                  0
8  6707eeb421bc4028575d55e3   293772                  0
9  6707eeb421bc4028575d55e4   294606                  0

  LocalAuthorityBusinessID                          BusinessName  \
0             PI/000025307                             Charlie's
1             PI/000034075               Mv City Cruises Erasmus
2             PI/000002614             Benfleet Motor Yacht Club
3             PI/000036464  Coombs Catering t/a The Lock and Key
4             PI/000014647              Tilbury Seafarers Centre
5             PI/000019066                            Mv Valulla
6             PI/000002538                         Tereza Joanne
7             PI/000029844                      Brick Lane Brews
8             PI/000002585         The Nuance Group (UK) Limited
9             PI/000016185                              WH Smith

              BusinessType  BusinessTypeID  \
0  Other catering premises            7841
1  Other catering premises            7841
2  Other catering premises            7841
3  Restaurant/Cafe/Canteen               1
4  Restaurant/Cafe/Canteen               1
5  Other catering premises            7841
6  Other catering premises            7841
7  Restaurant/Cafe/Canteen               1
8        Retailers - other            4613
9        Retailers - other            4613

                                        AddressLine1  \
0         Oak Apple Farm Building 103 Sheernes Docks
1                                 Cherry Garden Pier
2                                         Ferry Road
3                                  Leslie Ford House
4                          Tenants Row Tilbury Docks
5  Reeds River Cruises LtdKings ReachRiver Thames...
6  Funcraft UK Ltd King George V Dock Woolwich Ma...
7                       Air side London City Airport
8                  Duty Free Shop Passenger Terminal
9                                London City Airport

                           AddressLine2 AddressLine3  ...  \
0                           Sheppy Kent               ...
1      Cherry Garden Street Rotherhithe     Charlton  ...
2                  South Benfleet Essex               ...
3                               Tilbury     Charlton  ...
4                         Tilbury Essex               ...
5                                London               ...
6                                London               ...
7                                London               ...
8  London City AirportRoyal DocksLondon               ...
9                     Silvertown London               ...

                               LocalAuthorityWebSite  \
0  http://www.cityoflondon.gov.uk/Corporation/hom...
1  http://www.cityoflondon.gov.uk/Corporation/hom...
2  http://www.cityoflondon.gov.uk/Corporation/hom...
3  http://www.cityoflondon.gov.uk/Corporation/hom...
4  http://www.cityoflondon.gov.uk/Corporation/hom...
5  http://www.cityoflondon.gov.uk/Corporation/hom...
6  http://www.cityoflondon.gov.uk/Corporation/hom...
7  http://www.cityoflondon.gov.uk/Corporation/hom...
8  http://www.cityoflondon.gov.uk/Corporation/hom...
9  http://www.cityoflondon.gov.uk/Corporation/hom...

             LocalAuthorityEmailAddress  \
0  publicprotection@cityoflondon.gov.uk
1  publicprotection@cityoflondon.gov.uk
2  publicprotection@cityoflondon.gov.uk
3  publicprotection@cityoflondon.gov.uk
4  publicprotection@cityoflondon.gov.uk
5  publicprotection@cityoflondon.gov.uk
6  publicprotection@cityoflondon.gov.uk
7  publicprotection@cityoflondon.gov.uk
8  publicprotection@cityoflondon.gov.uk
9  publicprotection@cityoflondon.gov.uk

                                              scores  SchemeType  \
0  {'Hygiene': 5, 'Structural': 10, 'ConfidenceIn...        FHRS
1  {'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...        FHRS
2  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...        FHRS
3  {'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...        FHRS
4  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...        FHRS
5  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...        FHRS
6  {'Hygiene': 0, 'Structural': 5, 'ConfidenceInM...        FHRS
7  {'Hygiene': 10, 'Structural': 5, 'ConfidenceIn...        FHRS
8  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...        FHRS
9  {'Hygiene': 0, 'Structural': 0, 'ConfidenceInM...        FHRS

                                             geocode RightToReply  \
0     {'longitude': 0.508551, 'latitude': 51.369321}
1  {'longitude': 0.249255999922752, 'latitude': 5...
2     {'longitude': 0.561954, 'latitude': 51.543831}
3  {'longitude': 0.346336990594864, 'latitude': 5...
4     {'longitude': 0.346325, 'latitude': 51.464078}
5     {'longitude': 0.287555, 'latitude': 51.504071}
6     {'longitude': 0.069286, 'latitude': 51.501121}
7     {'longitude': 0.048006, 'latitude': 51.503733}
8     {'longitude': 0.047966, 'latitude': 51.504112}
9  {'longitude': 0.0479655750095844, 'latitude': ...

      Distance NewRatingPending  \
0  4627.439468            False
1  4627.873179            False
2  4631.968418            False
3  4636.846754            False
4  4636.847650            False
5  4640.460834            False
6  4648.301822            False
7  4649.173485            False
8  4649.188826            False
9  4649.188850            False

                                                meta  \
0  {'dataSource': None, 'extractDate': '0001-01-0...
1  {'dataSource': None, 'extractDate': '0001-01-0...
2  {'dataSource': None, 'extractDate': '0001-01-0...
3  {'dataSource': None, 'extractDate': '0001-01-0...
4  {'dataSource': None, 'extractDate': '0001-01-0...
5  {'dataSource': None, 'extractDate': '0001-01-0...
6  {'dataSource': None, 'extractDate': '0001-01-0...
7  {'dataSource': None, 'extractDate': '0001-01-0...
8  {'dataSource': None, 'extractDate': '0001-01-0...
9  {'dataSource': None, 'extractDate': '0001-01-0...

                                               links
0  [{'rel': 'self', 'href': 'https://api.ratings....
1  [{'rel': 'self', 'href': 'http://api.ratings.f...
2  [{'rel': 'self', 'href': 'http://api.ratings.f...
3  [{'rel': 'self', 'href': 'http://api.ratings.f...
4  [{'rel': 'self', 'href': 'http://api.ratings.f...
5  [{'rel': 'self', 'href': 'http://api.ratings.f...
6  [{'rel': 'self', 'href': 'http://api.ratings.f...
7  [{'rel': 'self', 'href': 'http://api.ratings.f...
8  [{'rel': 'self', 'href': 'http://api.ratings.f...
9  [{'rel': 'self', 'href': 'http://api.ratings.f...

[10 rows x 28 columns]

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [19]:
# Latitude and Longitude of Penang Flavours
latitude = 51.49014200
longitude = 0.08384000

# Defining the degree search range
degree_search = 0.01

# Defining the query to find establishments with RatingValue 5 within the latitude and longitude range
query = {
    "RatingValue": 5,
    "geocode.latitude": {"$gte": latitude - degree_search, "$lte": latitude + degree_search},
    "geocode.longitude": {"$gte": longitude - degree_search, "$lte": longitude + degree_search}
}

# Sorting by Hygiene score (ascending order)
sort = [("scores.Hygiene", 1)]

# Limiting the results to the top 5 establishments
limit = 5

# Retrieving the results
results = db.establishments.find(query).sort(sort).limit(limit)

# Printing the results
print("\nTop 5 establishments sorted by Hygiene score:")
for establishment in results:
    pprint({
        "Business Name": establishment['BusinessName'],
        "Address": f"{establishment['AddressLine1']}, {establishment.get('PostCode', 'No PostCode')}",
        "Rating Value": establishment['RatingValue'],
        "Hygiene Score": establishment['scores'].get('Hygiene', 'No Hygiene Score'),
        "Latitude": establishment['geocode']['latitude'],
        "Longitude": establishment['geocode']['longitude']
    })
    print("-" * 40)

Top 5 establishments sorted by Hygiene score:
{'Address': '130 - 132 Plumstead High Street, SE18 1JQ',
 'Business Name': 'Volunteer',
 'Hygiene Score': 0,
 'Latitude': 51.4873437,
 'Longitude': 0.09208,
 'Rating Value': 5}
----------------------------------------
{'Address': 'Plumstead Manor School Old Mill Road, SE18 1QG',
 'Business Name': 'Plumstead Manor Nursery',
 'Hygiene Score': 0,
 'Latitude': 51.481517791748,
 'Longitude': 0.0859939977526665,
 'Rating Value': 5}
----------------------------------------
{'Address': '17 Lakedale Road, SE18 1PP',
 'Business Name': 'Lumbini Grocery Ltd T/A Al-Iman',
 'Hygiene Score': 0,
 'Latitude': 51.4871632,
 'Longitude': 0.0916256,
 'Rating Value': 5}
----------------------------------------
{'Address': '144 - 146 Plumstead High Street, SE18 1JQ',
 'Business Name': 'Iceland',
 'Hygiene Score': 0,
 'Latitude': 51.4871482849121,
 'Longitude': 0.0924199968576431,
 'Rating Value': 5}
----------------------------------------
{'Address': 'Restaurant And Premises 107A Plumstead High Street, SE18 1SE',
 'Business Name': 'Howe and Co Fish and Chips - Van 17',
 'Hygiene Score': 0,
 'Latitude': 51.4875335693359,
 'Longitude': 0.0925370007753372,
 'Rating Value': 5}
----------------------------------------

In [26]:
# Re-running the query to get the top 5 establishments again
results = db.establishments.find(query).sort(sort).limit(limit)

# Converting results to a list of dictionaries
establishment_list = []
for establishment in results:
    establishment_list.append({
        "Business Name": establishment['BusinessName'],
        "Address": f"{establishment['AddressLine1']}, {establishment.get('PostCode', 'No PostCode')}",
        "Rating Value": establishment['RatingValue'],
        "Hygiene Score": establishment['scores'].get('Hygiene', 'No Hygiene Score'),
        "Latitude": establishment['geocode']['latitude'],
        "Longitude": establishment['geocode']['longitude']
    })

# Creating a DataFrame
df_establishments = pd.DataFrame(establishment_list)

# Displaying the DataFrame
print("\nDataFrame of Top 5 establishments sorted by Hygiene score:")
print(df_establishments)

DataFrame of Top 5 establishments sorted by Hygiene score:
                         Business Name  \
0                            Volunteer
1              Plumstead Manor Nursery
2      Lumbini Grocery Ltd T/A Al-Iman
3                              Iceland
4  Howe and Co Fish and Chips - Van 17

                                             Address  Rating Value  \
0          130 - 132 Plumstead High Street, SE18 1JQ             5
1     Plumstead Manor School Old Mill Road, SE18 1QG             5
2                         17 Lakedale Road, SE18 1PP             5
3          144 - 146 Plumstead High Street, SE18 1JQ             5
4  Restaurant And Premises 107A Plumstead High St...             5

   Hygiene Score   Latitude  Longitude
0              0  51.487344   0.092080
1              0  51.481518   0.085994
2              0  51.487163   0.091626
3              0  51.487148   0.092420
4              0  51.487534   0.092537

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [28]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
# 2. Groups the matches by Local Authority
# 3. Sorts the matches from highest to lowest

# Creating the aggregation pipeline
pipeline = [
    # Step 1: Match establishments with a hygiene score of 0
    {
        "$match": {
            "scores.Hygiene": 0
        }
    },
    # Step 2: Group by Local Authority and count the number of establishments
    {
        "$group": {
            "_id": "$LocalAuthorityName",  # Group by Local Authority
            "count": {"$sum": 1}           # Count the number of establishments
        }
    },
    # Step 3: Sort by count in descending order
    {
        "$sort": {
            "count": -1  # Sort from highest to lowest
        }
    }
]

# Executing the aggregation pipeline
results = db.establishments.aggregate(pipeline)

# Converting results to a list
result_list = list(results)

# Printing the number of documents in the result
print(f"Number of Local Authorities with establishments having a hygiene score of 0: {len(result_list)}")

# Printing the first 10 results
print("\nFirst 10 Local Authorities with hygiene score of 0:")
for authority in result_list[:10]:
    print(f"Local Authority: {authority['_id']}, Count: {authority['count']}")

Number of Local Authorities with establishments having a hygiene score of 0: 55

First 10 Local Authorities with hygiene score of 0:
Local Authority: Thanet, Count: 1130
Local Authority: Greenwich, Count: 882
Local Authority: Maidstone, Count: 713
Local Authority: Newham, Count: 711
Local Authority: Swale, Count: 686
Local Authority: Chelmsford, Count: 680
Local Authority: Medway, Count: 672
Local Authority: Bexley, Count: 607
Local Authority: Southend-On-Sea, Count: 586
Local Authority: Tendring, Count: 542

In [30]:
# Convert the result to a Pandas DataFrame
df_results = pd.DataFrame(result_list)
# Display the number of rows in the DataFrame
print(f"Number of rows in the DataFrame: {len(df_results)}")
# Display the first 10 rows of the DataFrame
print("\nFirst 10 rows of the DataFrame:")
print(df_results.head(10))

Number of rows in the DataFrame: 55

First 10 rows of the DataFrame:
               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542